INSERT INTO Compound Values ('Aluminum Nitrate', 'grams', 1, 10);
INSERT INTO Compound Values ('Carbon Dioxide', 'grams', 5, 20);
INSERT INTO Compound Values ('Potassium Cyanate', 'grams', 2, 30);
INSERT INTO Compound Values ('Mesoxalic Acid', 'grams', 10, 100);
INSERT INTO Compound Values ('Hydrochloric Acid', 'liters', .5, 2);
INSERT INTO Compound Values ('Sodium Chloride', 'liters', 1, 6);
INSERT INTO Compound Values ('Hydroxide', 'liters', .5, 6);
INSERT INTO Compound Values ('Sulfuric Acid', 'liters', 1, 3);
INSERT INTO Compound Values ('Palladium Hydride', 'grams', 2, 60);
INSERT INTO Compound Values ('Actin', 'grams', 50, 200);
INSERT INTO Compound Values ('Adenosine', 'liters', 20, 400);
INSERT INTO Compound Values ('Adonitol', 'liters', 1, 9);
INSERT INTO Compound Values ('Biotin', 'grams', 60, 100);
INSERT INTO Compound Values ('Caffeine', 'grams', 20, 60);
INSERT INTO Compound Values ('Dopamine', 'grams', 30, 50);
INSERT INTO Compound Values ('Eugenol', 'liters', .2, 1);
INSERT INTO Compound Values ('Gastrin', 'grams', 30, 90);
INSERT INTO Compound Values ('Histamine', 'liters', 3, 6);
INSERT INTO Compound Values ('Leptin', 'grams', 100, 200);
INSERT INTO Compound Values ('Mimosine', 'liters', .5, .8);